### ISSUE TITLE
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class

### ISSUE THREAD

**Issue by ulx** [AlexGilleran/IceSoap#4] opened 2016-04-11 13:23 UTC
Hi!
I have problem use gradle plugin 2.0 and multidex
How can I fix this?

```
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.jaxen.dom.DocumentNavigator$6) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.jaxen.dom.DocumentNavigator$1) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.

```

**Comment by AlexGilleran** [comment] 2016-04-11 14:07
Duplicate of #3

**Closed by AlexGilleran** 2016-04-11 14:07 UTC
